require( 'jszip' );
require( 'pdfmake' );
require("datatables.net");
require('datatables.net-dt' );
require('datatables.net-autofill-dt' );
require('datatables.net-buttons-dt' );
require('datatables.net-buttons/js/buttons.colVis.js' );
require('datatables.net-buttons/js/buttons.html5.js' );
require('datatables.net-buttons/js/buttons.print.js' );
require('datatables.net-colreorder-dt' );
require('datatables.net-datetime' );
require('datatables.net-fixedcolumns-dt' );
require('datatables.net-fixedheader-dt' );
require('datatables.net-keytable-dt' );
require('datatables.net-responsive-dt' );
require('datatables.net-rowgroup-dt' );
require('datatables.net-rowreorder-dt' );
require('datatables.net-scroller-dt' );
require('datatables.net-searchbuilder-dt' );
require('datatables.net-searchpanes-dt' );
require('datatables.net-select-dt' );